pipeline{
agent any
 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }

    }
    stage('upload artifact'){
        steps{
           sh 'curl -uadmin:AP8SXsm1zBZcPa5n1gHtZxEC8rM -T \
           target/bio*.jar \
                           
           "http://3.85.54.165:8081/artifactory/Geolocation/server/bio_${BUILD_ID}.jar"'
        }
    }
       
    }
}
    
