pipeline{
agent any
 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh curl -uadmin:AP2iyxENzwzsgdmvabhCYgxNvqe -T \
            target/bio*.jar \
            
             "http://100.26.228.124:8081/artifactory/Geolocation/geo/bio_${BUILD_ID}.jar"

             
            
        }
             
            
        }
    }
   }
