  pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage('sonar-scan'){
        steps{
            withSonarQubeEnv('sonarQube'){
        sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devops1958_geo-location'
            }
          
        
        }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        sh 'cat /etc/os-release'
        sh 'lsblk'
        }
    }     
 
   
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:APAtrqGdCmQEVEvzSAvbZF6a9tv -T \
            target/bio*.jar \
            "http://52.91.132.174:8081/artifactory/Geosolution/file1/bio-${BUILD_ID}.jar"'
        }
    }
    stage('docker login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin \
            781382313434.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
    stage('docker image build'){
        steps{
            sh 'docker build -t utc-app1:v.${BUILD-ID} .'
           // sh 'docker build -t utc-app1:latest'
        }
    }  
    stage('image tagging'){
        steps{
            sh 'docker tag utc-app1:v.${BUILD-ID} \
            781382313434.dkr.ecr.us-east-1.amazonaws.com/utc-app1:v.${BUILD-ID}'
            sh 'docker tag utc-app1:latest \
            781382313434.dkr.ecr.us-east-1.amazonaws.com/utc-app1:latest'
            
        }
    }  
    stage(' push image'){
        steps{
           // sh 'docker push 781382313434.dkr.ecr.us-east-1.amazonaws.com/utc-app1:latest'
            sh 'docker push 781382313434.dkr.ecr.us-east-1.amazonaws.com/utc-app1:v.${BUILD-ID}'
        }
    }
       
    }
}
    
